madv_free: add -pthread both CFLAGS and LDFLAGS
Instead of add -lpthread to LDFLAGS, add -pthread both to CLAGS and LDFLAGS prevent followed errors.

 -lpthread -ljemalloc  ebizzy_madv.o   -o ebizzy_madv
 ebizzy_madv.o: In function `start_threads':
 ebizzy_madv.c:(.text+0xc49): undefined reference to `pthread_create'
 ebizzy_madv.c:(.text+0xd42): undefined reference to `pthread_join'
 collect2: error: ld returned 1 exit status
 <builtin>: recipe for target 'ebizzy_madv' failed
 make: *** [ebizzy_madv] Error 1